import 'package:flutter/cupertino.dart';

import 'product.dart';

class ProductsProvider with ChangeNotifier {
  List<Product> get products {
    return [..._products];
  }

  void updateProducts(int index, Product product) {
    _products[index] = product;
  }

  void shuffleProducts() {
    _products.shuffle();
  }

  final _products = [
    Product(
        id: 0,
        title: 'Chain Sprocket Kit',
        brand: 'Honda',
        image: 'images/Chain Sprocket Kit.PNG',
        price: 20),
    Product(
        id: 1,
        title: 'Piston Kit',
        brand: 'Honda',
        image: 'images/Piston Kit.PNG',
        price: 20),
    Product(
        id: 3,
        title: 'Headlight',
        brand: 'Honda',
        image: 'images/Headlight.PNG',
        price: 20),
    Product(
        id: 4,
        title: 'Element Air Cleaner',
        brand: 'Honda',
        image: 'images/Element Air Cleaner.PNG',
        price: 20),
    Product(
        id: 5,
        title: 'Brake Shoe Set',
        brand: 'Honda',
        image: 'images/Brake Shoe Set.PNG',
        price: 20),
    Product(
        id: 6,
        title: 'Chain Cover Set',
        brand: 'Honda',
        image: 'images/Chain Cover Set.PNG',
        price: 20),
    Product(
        id: 7,
        title: 'Shock Absorber',
        brand: 'Honda',
        image: 'images/Shock Absorber.PNG',
        price: 20),
    Product(
        id: 8,
        title: 'Clutch Friction Plate',
        brand: 'Honda',
        image: 'images/Clutch Friction Plate.PNG',
        price: 20),
    Product(
        id: 9,
        title: 'Front Wheel Hub',
        brand: 'Honda',
        image: 'images/Front Wheel Hub.PNG',
        price: 20),
    Product(
        id: 10,
        title: 'Muffler',
        brand: 'Honda',
        image: 'images/Muffler.PNG',
        price: 20),
    Product(
        id: 11,
        title: 'Double Seat',
        brand: 'Honda',
        image: 'images/Double Seat.PNG',
        price: 20),
    Product(
        id: 12,
        title: 'Speedometer',
        brand: 'Honda',
        image: 'images/Speedometer.PNG',
        price: 20),
    Product(
        id: 13,
        title: 'Spokes and Nipples',
        brand: 'Honda',
        image: 'images/Spokes and Nipples.PNG',
        price: 20),
    Product(
        id: 14,
        title: 'Front Brake Cable',
        brand: 'Honda',
        image: 'images/Front Brake Cable.PNG',
        price: 20),
    Product(
        id: 15,
        title: 'Connecting Rod Kit',
        brand: 'Honda',
        image: 'images/Connecting Rod Kit.PNG',
        price: 20),
    Product(
        id: 16,
        title: 'Spark Plug',
        brand: 'Honda',
        image: 'images/Spark Plug.PNG',
        price: 20),
    Product(
        id: 17,
        title: 'Tyre',
        brand: 'Honda',
        image: 'images/Tyre.PNG',
        price: 20),
    Product(
        id: 18,
        title: 'Chain Sprocket Kit',
        brand: 'Indian Motorcycle',
        image: 'images/Chain Sprocket Kit.PNG',
        price: 20),
    Product(
        id: 19,
        title: 'Piston Kit',
        brand: 'Indian Motorcycle',
        image: 'images/Piston Kit.PNG',
        price: 20),
    Product(
        id: 21,
        title: 'Headlight',
        brand: 'Indian Motorcycle',
        image: 'images/Headlight.PNG',
        price: 20),
    Product(
        id: 22,
        title: 'Element Air Cleaner',
        brand: 'Indian Motorcycle',
        image: 'images/Element Air Cleaner.PNG',
        price: 20),
    Product(
        id: 23,
        title: 'Brake Shoe Set',
        brand: 'Indian Motorcycle',
        image: 'images/Brake Shoe Set.PNG',
        price: 20),
    Product(
        id: 24,
        title: 'Chain Cover Set',
        brand: 'Indian Motorcycle',
        image: 'images/Chain Cover Set.PNG',
        price: 20),
    Product(
        id: 25,
        title: 'Shock Absorber',
        brand: 'Indian Motorcycle',
        image: 'images/Shock Absorber.PNG',
        price: 20),
    Product(
        id: 26,
        title: 'Clutch Friction Plate',
        brand: 'Indian Motorcycle',
        image: 'images/Clutch Friction Plate.PNG',
        price: 20),
    Product(
        id: 27,
        title: 'Front Wheel Hub',
        brand: 'Indian Motorcycle',
        image: 'images/Front Wheel Hub.PNG',
        price: 20),
    Product(
        id: 28,
        title: 'Muffler',
        brand: 'Indian Motorcycle',
        image: 'images/Muffler.PNG',
        price: 20),
    Product(
        id: 29,
        title: 'Double Seat',
        brand: 'Indian Motorcycle',
        image: 'images/Double Seat.PNG',
        price: 20),
    Product(
        id: 30,
        title: 'Speedometer',
        brand: 'Indian Motorcycle',
        image: 'images/Speedometer.PNG',
        price: 20),
    Product(
        id: 31,
        title: 'Spokes and Nipples',
        brand: 'Indian Motorcycle',
        image: 'images/Spokes and Nipples.PNG',
        price: 20),
    Product(
        id: 32,
        title: 'Front Brake Cable',
        brand: 'Indian Motorcycle',
        image: 'images/Front Brake Cable.PNG',
        price: 20),
    Product(
        id: 33,
        title: 'Connecting Rod Kit',
        brand: 'Indian Motorcycle',
        image: 'images/Connecting Rod Kit.PNG',
        price: 20),
    Product(
        id: 34,
        title: 'Spark Plug',
        brand: 'Indian Motorcycle',
        image: 'images/Spark Plug.PNG',
        price: 20),
    Product(
        id: 35,
        title: 'Tyre',
        brand: 'Indian Motorcycle',
        image: 'images/Tyre.PNG',
        price: 20),
    Product(
        id: 36,
        title: 'Chain Sprocket Kit',
        brand: 'BMW',
        image: 'images/Chain Sprocket Kit.PNG',
        price: 20),
    Product(
        id: 37,
        title: 'Piston Kit',
        brand: 'BMW',
        image: 'images/Piston Kit.PNG',
        price: 20),
    Product(
        id: 39,
        title: 'Headlight',
        brand: 'BMW',
        image: 'images/Headlight.PNG',
        price: 20),
    Product(
        id: 40,
        title: 'Element Air Cleaner',
        brand: 'BMW',
        image: 'images/Element Air Cleaner.PNG',
        price: 20),
    Product(
        id: 41,
        title: 'Brake Shoe Set',
        brand: 'BMW',
        image: 'images/Brake Shoe Set.PNG',
        price: 20),
    Product(
        id: 42,
        title: 'Chain Cover Set',
        brand: 'BMW',
        image: 'images/Chain Cover Set.PNG',
        price: 20),
    Product(
        id: 43,
        title: 'Shock Absorber',
        brand: 'BMW',
        image: 'images/Shock Absorber.PNG',
        price: 20),
    Product(
        id: 44,
        title: 'Clutch Friction Plate',
        brand: 'BMW',
        image: 'images/Clutch Friction Plate.PNG',
        price: 20),
    Product(
        id: 45,
        title: 'Front Wheel Hub',
        brand: 'BMW',
        image: 'images/Front Wheel Hub.PNG',
        price: 20),
    Product(
        id: 46,
        title: 'Muffler',
        brand: 'BMW',
        image: 'images/Muffler.PNG',
        price: 20),
    Product(
        id: 47,
        title: 'Double Seat',
        brand: 'BMW',
        image: 'images/Double Seat.PNG',
        price: 20),
    Product(
        id: 48,
        title: 'Speedometer',
        brand: 'BMW',
        image: 'images/Speedometer.PNG',
        price: 20),
    Product(
        id: 49,
        title: 'Spokes and Nipples',
        brand: 'BMW',
        image: 'images/Spokes and Nipples.PNG',
        price: 20),
    Product(
        id: 50,
        title: 'Front Brake Cable',
        brand: 'BMW',
        image: 'images/Front Brake Cable.PNG',
        price: 20),
    Product(
        id: 51,
        title: 'Connecting Rod Kit',
        brand: 'BMW',
        image: 'images/Connecting Rod Kit.PNG',
        price: 20),
    Product(
        id: 52,
        title: 'Spark Plug',
        brand: 'BMW',
        image: 'images/Spark Plug.PNG',
        price: 20),
    Product(
        id: 53,
        title: 'Tyre',
        brand: 'BMW',
        image: 'images/Tyre.PNG',
        price: 20),
    Product(
        id: 54,
        title: 'Chain Sprocket Kit',
        brand: 'Yamaha',
        image: 'images/Chain Sprocket Kit.PNG',
        price: 20),
    Product(
        id: 55,
        title: 'Piston Kit',
        brand: 'Yamaha',
        image: 'images/Piston Kit.PNG',
        price: 20),
    Product(
        id: 57,
        title: 'Headlight',
        brand: 'Yamaha',
        image: 'images/Headlight.PNG',
        price: 20),
    Product(
        id: 58,
        title: 'Element Air Cleaner',
        brand: 'Yamaha',
        image: 'images/Element Air Cleaner.PNG',
        price: 20),
    Product(
        id: 59,
        title: 'Brake Shoe Set',
        brand: 'Yamaha',
        image: 'images/Brake Shoe Set.PNG',
        price: 20),
    Product(
        id: 60,
        title: 'Chain Cover Set',
        brand: 'Yamaha',
        image: 'images/Chain Cover Set.PNG',
        price: 20),
    Product(
        id: 61,
        title: 'Shock Absorber',
        brand: 'Yamaha',
        image: 'images/Shock Absorber.PNG',
        price: 20),
    Product(
        id: 62,
        title: 'Clutch Friction Plate',
        brand: 'Yamaha',
        image: 'images/Clutch Friction Plate.PNG',
        price: 20),
    Product(
        id: 63,
        title: 'Front Wheel Hub',
        brand: 'Yamaha',
        image: 'images/Front Wheel Hub.PNG',
        price: 20),
    Product(
        id: 64,
        title: 'Muffler',
        brand: 'Yamaha',
        image: 'images/Muffler.PNG',
        price: 20),
    Product(
        id: 65,
        title: 'Double Seat',
        brand: 'Yamaha',
        image: 'images/Double Seat.PNG',
        price: 20),
    Product(
        id: 66,
        title: 'Speedometer',
        brand: 'Yamaha',
        image: 'images/Speedometer.PNG',
        price: 20),
    Product(
        id: 67,
        title: 'Spokes and Nipples',
        brand: 'Yamaha',
        image: 'images/Spokes and Nipples.PNG',
        price: 20),
    Product(
        id: 68,
        title: 'Front Brake Cable',
        brand: 'Yamaha',
        image: 'images/Front Brake Cable.PNG',
        price: 20),
    Product(
        id: 69,
        title: 'Connecting Rod Kit',
        brand: 'Yamaha',
        image: 'images/Connecting Rod Kit.PNG',
        price: 20),
    Product(
        id: 70,
        title: 'Spark Plug',
        brand: 'Yamaha',
        image: 'images/Spark Plug.PNG',
        price: 20),
    Product(
        id: 71,
        title: 'Tyre',
        brand: 'Yamaha',
        image: 'images/Tyre.PNG',
        price: 20),
    Product(
        id: 72,
        title: 'Chain Sprocket Kit',
        brand: 'Suzuki',
        image: 'images/Chain Sprocket Kit.PNG',
        price: 20),
    Product(
        id: 73,
        title: 'Piston Kit',
        brand: 'Suzuki',
        image: 'images/Piston Kit.PNG',
        price: 20),
    Product(
        id: 75,
        title: 'Headlight',
        brand: 'Suzuki',
        image: 'images/Headlight.PNG',
        price: 20),
    Product(
        id: 76,
        title: 'Element Air Cleaner',
        brand: 'Suzuki',
        image: 'images/Element Air Cleaner.PNG',
        price: 20),
    Product(
        id: 77,
        title: 'Brake Shoe Set',
        brand: 'Suzuki',
        image: 'images/Brake Shoe Set.PNG',
        price: 20),
    Product(
        id: 78,
        title: 'Chain Cover Set',
        brand: 'Suzuki',
        image: 'images/Chain Cover Set.PNG',
        price: 20),
    Product(
        id: 79,
        title: 'Shock Absorber',
        brand: 'Suzuki',
        image: 'images/Shock Absorber.PNG',
        price: 20),
    Product(
        id: 80,
        title: 'Clutch Friction Plate',
        brand: 'Suzuki',
        image: 'images/Clutch Friction Plate.PNG',
        price: 20),
    Product(
        id: 81,
        title: 'Front Wheel Hub',
        brand: 'Suzuki',
        image: 'images/Front Wheel Hub.PNG',
        price: 20),
    Product(
        id: 82,
        title: 'Muffler',
        brand: 'Suzuki',
        image: 'images/Muffler.PNG',
        price: 20),
    Product(
        id: 83,
        title: 'Double Seat',
        brand: 'Suzuki',
        image: 'images/Double Seat.PNG',
        price: 20),
    Product(
        id: 84,
        title: 'Speedometer',
        brand: 'Suzuki',
        image: 'images/Speedometer.PNG',
        price: 20),
    Product(
        id: 85,
        title: 'Spokes and Nipples',
        brand: 'Suzuki',
        image: 'images/Spokes and Nipples.PNG',
        price: 20),
    Product(
        id: 86,
        title: 'Front Brake Cable',
        brand: 'Suzuki',
        image: 'images/Front Brake Cable.PNG',
        price: 20),
    Product(
        id: 87,
        title: 'Connecting Rod Kit',
        brand: 'Suzuki',
        image: 'images/Connecting Rod Kit.PNG',
        price: 20),
    Product(
        id: 88,
        title: 'Spark Plug',
        brand: 'Suzuki',
        image: 'images/Spark Plug.PNG',
        price: 20),
    Product(
        id: 89,
        title: 'Tyre',
        brand: 'Suzuki',
        image: 'images/Tyre.PNG',
        price: 20),
    Product(
        id: 90,
        title: 'Chain Sprocket Kit',
        brand: 'Aprilia',
        image: 'images/Chain Sprocket Kit.PNG',
        price: 20),
    Product(
        id: 91,
        title: 'Piston Kit',
        brand: 'Aprilia',
        image: 'images/Piston Kit.PNG',
        price: 20),
    Product(
        id: 93,
        title: 'Headlight',
        brand: 'Aprilia',
        image: 'images/Headlight.PNG',
        price: 20),
    Product(
        id: 94,
        title: 'Element Air Cleaner',
        brand: 'Aprilia',
        image: 'images/Element Air Cleaner.PNG',
        price: 20),
    Product(
        id: 95,
        title: 'Brake Shoe Set',
        brand: 'Aprilia',
        image: 'images/Brake Shoe Set.PNG',
        price: 20),
    Product(
        id: 96,
        title: 'Chain Cover Set',
        brand: 'Aprilia',
        image: 'images/Chain Cover Set.PNG',
        price: 20),
    Product(
        id: 97,
        title: 'Shock Absorber',
        brand: 'Aprilia',
        image: 'images/Shock Absorber.PNG',
        price: 20),
    Product(
        id: 98,
        title: 'Clutch Friction Plate',
        brand: 'Aprilia',
        image: 'images/Clutch Friction Plate.PNG',
        price: 20),
    Product(
        id: 99,
        title: 'Front Wheel Hub',
        brand: 'Aprilia',
        image: 'images/Front Wheel Hub.PNG',
        price: 20),
    Product(
        id: 100,
        title: 'Muffler',
        brand: 'Aprilia',
        image: 'images/Muffler.PNG',
        price: 20),
    Product(
        id: 101,
        title: 'Double Seat',
        brand: 'Aprilia',
        image: 'images/Double Seat.PNG',
        price: 20),
    Product(
        id: 102,
        title: 'Speedometer',
        brand: 'Aprilia',
        image: 'images/Speedometer.PNG',
        price: 20),
    Product(
        id: 103,
        title: 'Spokes and Nipples',
        brand: 'Aprilia',
        image: 'images/Spokes and Nipples.PNG',
        price: 20),
    Product(
        id: 104,
        title: 'Front Brake Cable',
        brand: 'Aprilia',
        image: 'images/Front Brake Cable.PNG',
        price: 20),
    Product(
        id: 105,
        title: 'Connecting Rod Kit',
        brand: 'Aprilia',
        image: 'images/Connecting Rod Kit.PNG',
        price: 20),
    Product(
        id: 106,
        title: 'Spark Plug',
        brand: 'Aprilia',
        image: 'images/Spark Plug.PNG',
        price: 20),
    Product(
        id: 107,
        title: 'Tyre',
        brand: 'Aprilia',
        image: 'images/Tyre.PNG',
        price: 20),
    Product(
        id: 108,
        title: 'Chain Sprocket Kit',
        brand: 'Harley-Davidson',
        image: 'images/Chain Sprocket Kit.PNG',
        price: 20),
    Product(
        id: 109,
        title: 'Piston Kit',
        brand: 'Harley-Davidson',
        image: 'images/Piston Kit.PNG',
        price: 20),
    Product(
        id: 111,
        title: 'Headlight',
        brand: 'Harley-Davidson',
        image: 'images/Headlight.PNG',
        price: 20),
    Product(
        id: 112,
        title: 'Element Air Cleaner',
        brand: 'Harley-Davidson',
        image: 'images/Element Air Cleaner.PNG',
        price: 20),
    Product(
        id: 113,
        title: 'Brake Shoe Set',
        brand: 'Harley-Davidson',
        image: 'images/Brake Shoe Set.PNG',
        price: 20),
    Product(
        id: 114,
        title: 'Chain Cover Set',
        brand: 'Harley-Davidson',
        image: 'images/Chain Cover Set.PNG',
        price: 20),
    Product(
        id: 115,
        title: 'Shock Absorber',
        brand: 'Harley-Davidson',
        image: 'images/Shock Absorber.PNG',
        price: 20),
    Product(
        id: 116,
        title: 'Clutch Friction Plate',
        brand: 'Harley-Davidson',
        image: 'images/Clutch Friction Plate.PNG',
        price: 20),
    Product(
        id: 117,
        title: 'Front Wheel Hub',
        brand: 'Harley-Davidson',
        image: 'images/Front Wheel Hub.PNG',
        price: 20),
    Product(
        id: 118,
        title: 'Muffler',
        brand: 'Harley-Davidson',
        image: 'images/Muffler.PNG',
        price: 20),
    Product(
        id: 119,
        title: 'Double Seat',
        brand: 'Harley-Davidson',
        image: 'images/Double Seat.PNG',
        price: 20),
    Product(
        id: 120,
        title: 'Speedometer',
        brand: 'Harley-Davidson',
        image: 'images/Speedometer.PNG',
        price: 20),
    Product(
        id: 121,
        title: 'Spokes and Nipples',
        brand: 'Harley-Davidson',
        image: 'images/Spokes and Nipples.PNG',
        price: 20),
    Product(
        id: 122,
        title: 'Front Brake Cable',
        brand: 'Harley-Davidson',
        image: 'images/Front Brake Cable.PNG',
        price: 20),
    Product(
        id: 123,
        title: 'Connecting Rod Kit',
        brand: 'Harley-Davidson',
        image: 'images/Connecting Rod Kit.PNG',
        price: 20),
    Product(
        id: 124,
        title: 'Spark Plug',
        brand: 'Harley-Davidson',
        image: 'images/Spark Plug.PNG',
        price: 20),
    Product(
        id: 125,
        title: 'Tyre',
        brand: 'Harley-Davidson',
        image: 'images/Tyre.PNG',
        price: 20),
    Product(
        id: 126,
        title: 'Chain Sprocket Kit',
        brand: 'Ducati',
        image: 'images/Chain Sprocket Kit.PNG',
        price: 20),
    Product(
        id: 127,
        title: 'Piston Kit',
        brand: 'Ducati',
        image: 'images/Piston Kit.PNG',
        price: 20),
    Product(
        id: 129,
        title: 'Headlight',
        brand: 'Ducati',
        image: 'images/Headlight.PNG',
        price: 20),
    Product(
        id: 130,
        title: 'Element Air Cleaner',
        brand: 'Ducati',
        image: 'images/Element Air Cleaner.PNG',
        price: 20),
    Product(
        id: 131,
        title: 'Brake Shoe Set',
        brand: 'Ducati',
        image: 'images/Brake Shoe Set.PNG',
        price: 20),
    Product(
        id: 132,
        title: 'Chain Cover Set',
        brand: 'Ducati',
        image: 'images/Chain Cover Set.PNG',
        price: 20),
    Product(
        id: 133,
        title: 'Shock Absorber',
        brand: 'Ducati',
        image: 'images/Shock Absorber.PNG',
        price: 20),
    Product(
        id: 134,
        title: 'Clutch Friction Plate',
        brand: 'Ducati',
        image: 'images/Clutch Friction Plate.PNG',
        price: 20),
    Product(
        id: 135,
        title: 'Front Wheel Hub',
        brand: 'Ducati',
        image: 'images/Front Wheel Hub.PNG',
        price: 20),
    Product(
        id: 136,
        title: 'Muffler',
        brand: 'Ducati',
        image: 'images/Muffler.PNG',
        price: 20),
    Product(
        id: 137,
        title: 'Double Seat',
        brand: 'Ducati',
        image: 'images/Double Seat.PNG',
        price: 20),
    Product(
        id: 138,
        title: 'Speedometer',
        brand: 'Ducati',
        image: 'images/Speedometer.PNG',
        price: 20),
    Product(
        id: 139,
        title: 'Spokes and Nipples',
        brand: 'Ducati',
        image: 'images/Spokes and Nipples.PNG',
        price: 20),
    Product(
        id: 140,
        title: 'Front Brake Cable',
        brand: 'Ducati',
        image: 'images/Front Brake Cable.PNG',
        price: 20),
    Product(
        id: 141,
        title: 'Connecting Rod Kit',
        brand: 'Ducati',
        image: 'images/Connecting Rod Kit.PNG',
        price: 20),
    Product(
        id: 142,
        title: 'Spark Plug',
        brand: 'Ducati',
        image: 'images/Spark Plug.PNG',
        price: 20),
    Product(
        id: 143,
        title: 'Tyre',
        brand: 'Ducati',
        image: 'images/Tyre.PNG',
        price: 20),
  ];
}
